version: "3.9"

services:
  postgres:
    image: postgres:10
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow-local-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    networks:
      - bds-network
    restart: always

  airflow-webserver:
    image: airflow-base
    build:
      dockerfile: ./airflow/Dockerfile
      context: .
    command: webserver
    volumes:
      - ../covid-app/src:../covid-app/src/
      - ../covid-app/src/carga:../covid-app/src/carga/
      - ../covid-app/src/utils:../covid-app/src/utils/
      - ../airflow/dags:../airflow/dags
      - ../airflow/logs:../airflow/logs
      - ../airflow/plugins:../airflow/plugins
    ports:
      - 8280:8080
    networks:
      - bds-network
    environment:
      _AIRFLOW_DB_UPGRADE: 'true'
      _AIRFLOW_WWW_USER_CREATE: 'true'
      _AIRFLOW_WWW_USER_USERNAME: 'airflow'
      _AIRFLOW_WWW_USER_PASSWORD: 'airflow'
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    restart: always
  
  airflow-scheduler:
    image: airflow-base
    build:
      dockerfile: Dockerfile
      context: .
    command: scheduler
    networks:
      - bds-network
    volumes:
      - ../covid-app/src:../covid-app/src/
      - ../covid-app/src/carga:../covid-app/src/carga/
      - ../covid-app/src/utils:../covid-app/src/utils/
      - ../airflow/dags:../airflow/dags
      - ../airflow/logs:../airflow/logs
      - ../airflow/plugins:../airflow/plugins
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
      AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    restart: always
  
  ####### HADOOP
  hadoop-namenode:
    container_name: hadoop-namenode
    restart: always
    build: ./hadoop/namenode
    ports:
      - 9870:9870
      - 9000:9000
    networks:
      - bds-network
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop/hadoop.env

  hadoop-datanode:
    container_name: hadoop-datanode
    restart: always
    build: ./hadoop/datanode
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
     - bds-network
    environment:
      SERVICE_PRECONDITION: "hadoop-namenode:9870"
    env_file:
      - ./hadoop/hadoop.env

  hadoop-resourcemanager:
    container_name: hadoop-resourcemanager
    restart: always
    build: ./hadoop/resourcemanager
    networks:
     - bds-network
    environment:
      SERVICE_PRECONDITION: "hadoop-namenode:9000 hadoop-namenode:9870 hadoop-datanode:9864"
    env_file:
      - ./hadoop/hadoop.env

  hadoop-nodemanager-1:
    container_name: hadoop-nodemanager-1
    restart: always
    build: ./hadoop/nodemanager
    networks:
     - bds-network
    environment:
      SERVICE_PRECONDITION: "hadoop-namenode:9000 hadoop-namenode:9870 hadoop-datanode:9864 hadoop-resourcemanager:8088"
    env_file:
      - ./hadoop/hadoop.env

  ####### SPARK
  spark-master:
    build: ./spark/master
    container_name: spark-master
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - bds-network
    volumes:
      - shared-workspace:/opt/workspace
      - ../covid-app/src:/covid-app/src
      - ../covid-app/src/carga:/covid-app/src/carga/
      - ../covid-app/src/utils:/covid-app/src/utils/

  spark-worker-1:
    build: ./spark/worker
    container_name: spark-worker-1
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    networks:
      - bds-network
    volumes:
      - shared-workspace:/opt/workspace
      - ../covid-app/src:/covid-app/src
      - ../covid-app/src/carga:/covid-app/src/carga/
      - ../covid-app/src/utils:/covid-app/src/utils/
  
    depends_on:
      - spark-master

  spark-worker-2:
    build: ./spark/worker
    container_name: spark-worker-2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512mm
    networks:
      - bds-network
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
      - ../covid-app/src:../covid-app/src
      - ../covid-app/src/carga:../covid-app/src/carga/
      - ../covid-app/src/utils:../covid-app/src/utils/

    depends_on:
      - spark-master

####### JUPYTER
  jupyter-notebook:
    build: ./jupyter
    container_name: jupyter-notebook
    ports:
      - 8888:8888
      - 4040:4040
    networks:
     - bds-network
    volumes:
      - shared-workspace:/opt/workspace

volumes:
  airflow-local-db-volume:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local

networks:
  bds-network:
    external: true
